#!/bin/bash

if [[ $UID != 0 ]]; then
    echo "Please run this script with sudo:"
    echo "sudo $0 $*"
    exit 1
fi

connectionName="$1"

# Handle VPN
nmcli con show --active | grep "$connectionName"

if [[ $? -ne 0 ]]
then
  echo "Not connected to VPN."
  exit 1
fi

# Start Client
echo "Starting daemon..."
systemctl start transmission-daemon

if [[ $? -ne 0 ]]
then
  echo "Failed to start daemon."
  exit 2
fi

echo "Started daemon."

# Stop daemon on exit
function finish {
  systemctl stop transmission-daemon
  echo "Stopped daemon."
}
trap finish EXIT

# Stop daemon when VPN disconnects
echo "Monitoring VPN..."
{
    dbus-monitor --system "type='signal',interface='org.freedesktop.NetworkManager.VPN.Connection',member='VpnStateChanged'" |
      {
        (while read -r line
         do
           if [ x"$(echo "$line" | grep 'uint32 7')" != x ]
           then
             echo "VPN disconnect detected."
             systemctl stop transmission-daemon
             echo "Stopped daemon."
             exit 0
           fi
         done)
      }
  }
