#!/bin/bash
if [ "$#" -eq 1 ]; then
  youtube-dl --extract-audio --audio-format mp3 $1
elif [ "$#" -eq 2 ]; then
  youtube-dl --extract-audio --audio-format mp3 -o "$2.%(ext)s" $1
else
  echo "Expected 1 or 2 arguments, but got $#"
fi
